# Change these first
owner: abusayed0206 # Your GitHub organization or username, where this repository lives
repo: cuetconnect-statuspage # The name of this repository

sites:
  - name: CUETCONNECT(MainSite)
    url: https://cuetconnect.org/
  - name: CUETCONNECT(ForumSite)
    url: https://forum.cuetconnect.org/
  - name: CUETCONNECT(AdmissionSite)
    url: https://admission.cuetconnect.org/
  - name: CUETCONNECT(NoticesSite)
    url: https://notices.cuetconnect.org/
  - name: CUETCONNECT(ShopSite)
    url: https://shop.cuetconnect.org/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cuetconnect.org
  # baseUrl: /your-repo-name
  logoUrl: https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/CUET_Vector_ogo.svg/170px-CUET_Vector_ogo.svg.png
  name: CONNECT🤟|Status Page
  introTitle: "A website for monitoring **CUET CONNECT** traffic"
  introMessage: Thanks to all contributors of @upptime/upptime
  navbar:
    - title: CUET
      href: https://cuetconnect.org/
    - title: Status(BackUp)
      href: https://statuspage.cuetconnect.org/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
